// scripts/gen-keyword-help.ts — src/ui/keywordHelp.ts の KEYWORD_HELP を Unity の C# (Assets/Game/KeywordHelp.g.cs) へ生成する (2026-09-07 M2)。
// 用語解説の一次資料は TS 側 (表示網羅テストが守る)。Unity のツールチップは生成物を読むだけ。手で編集しない。
import { writeFileSync } from 'node:fs'
import { KEYWORD_HELP } from '../src/ui/keywordHelp.ts'

const esc = (s: string) => s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n')
const lines: string[] = []
lines.push('// KeywordHelp.g.cs — scripts/gen-keyword-help.ts が src/ui/keywordHelp.ts から生成。手で編集しない。')
lines.push('using System.Collections.Generic;')
lines.push('')
lines.push('namespace DeckRogue.Game')
lines.push('{')
lines.push('    public static class KeywordHelp')
lines.push('    {')
lines.push('        public static readonly Dictionary<string, string> Terms = new Dictionary<string, string>')
lines.push('        {')
for (const [k, v] of Object.entries(KEYWORD_HELP)) lines.push(`            { "${esc(k)}", "${esc(v)}" },`)
lines.push('        };')
lines.push('')
lines.push('        /// <summary>文中に含まれる用語を長い順に探す (「呪いの烙印」が「烙印」より先に当たるように)</summary>')
lines.push('        public static List<string> FindIn(string text)')
lines.push('        {')
lines.push('            var found = new List<string>();')
lines.push('            if (string.IsNullOrEmpty(text)) return found;')
lines.push('            foreach (var k in Keys) if (text.Contains(k) && !found.Contains(k)) found.Add(k);')
lines.push('            return found;')
lines.push('        }')
lines.push('')
lines.push('        static List<string> _keys;')
lines.push('        static List<string> Keys')
lines.push('        {')
lines.push('            get')
lines.push('            {')
lines.push('                if (_keys == null) { _keys = new List<string>(Terms.Keys); _keys.Sort((a, b) => b.Length.CompareTo(a.Length)); }')
lines.push('                return _keys;')
lines.push('            }')
lines.push('        }')
lines.push('    }')
lines.push('}')
writeFileSync('unity/Assets/Game/KeywordHelp.g.cs', lines.join('\n') + '\n')
console.log(`KeywordHelp.g.cs: ${Object.keys(KEYWORD_HELP).length} 語`)
